name: build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install tox and poetry
      run: |
        # pipes do not work in GitHub Actions?
        # pip freeze | xargs pip uninstall -y
        pip install --upgrade pip
        pip install --upgrade setuptools wheel tox tox-poetry tox-gh-actions
        export POETRY_VERSION=1.2.0
        wget --output-document=install-poetry.py https://install.python-poetry.org
        python "install-poetry.py"
        # Adding `poetry` to `$PATH`:
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
        poetry config installer.parallel false
        poetry config experimental.new-installer false
        # poetry config virtualenvs.in-project true
        # poetry config virtualenvs.prefer-active-python true
        cat "$HOME/.config/pypoetry/config.toml"

    - name: Test with tox
      run: tox
