name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install Poetry
      run: |
        pip install --upgrade pip
        pip install --upgrade setuptools wheel
        export POETRY_VERSION=1.3.1
        wget --output-document=install-poetry.py https://install.python-poetry.org
        python "install-poetry.py"
        rm -f "install-poetry.py"
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
        poetry config installer.parallel true

    - name: Publish tagged release
      run: |
        # POETRY_PYPI_TOKEN_PYPI should be set in environment variables
        poetry publish --build
